// // /*
// // Auto-generated by: https://github.com/pmndrs/gltfjsx
// // Command: npx gltfjsx@6.5.3 computer-optimized.glb -T 
// // Files: computer-optimized.glb [486.38KB] > D:\languages\web_learning\ReactJs\ProjectPortfolio\public\models\computer-optimized-transformed.glb [39.72KB] (92%)
// // */

// import React from 'react'
// import { useGLTF } from '@react-three/drei'
// import { useFrame } from '@react-three/fiber'

// export function Computer(props) {
  
//   const { nodes, materials } = useGLTF('/models/computer-optimized-transformed.glb')
//   // useFrame(()=>{
//   //   if(group){
//   //   group.current.rotation.y+=.005
//     // }
//   // })
//   return (
//     <group {...props} dispose={null}>
//       <group position={[-4.005, 67.549, 58.539]}>
//         <mesh castShadow receiveShadow  geometry={nodes.Cube000_ComputerDesk_0001_1.geometry} material={materials['ComputerDesk.001']} />
//         <mesh castShadow  receiveShadow geometry={nodes.Cube000_ComputerDesk_0001_2.geometry} material={materials['FloppyDisk.001']} />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('models/computer-optimized-transformed.glb')

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Computer(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/computer-optimized-transformed.glb')

  // Auto-rotate the entire model without affecting light or camera
  useFrame(() => {
    if (group.current) {
      group.current.rotation.y += 0.005
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-4.005, 67.549, 58.539]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube000_ComputerDesk_0001_1.geometry}
          material={materials['ComputerDesk.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube000_ComputerDesk_0001_2.geometry}
          material={materials['FloppyDisk.001']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/computer-optimized-transformed.glb')
